load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "datatypes",
    hdrs = [
        "lane.h",
        "path_planning.h",
        "sensor_fusion.h",
        "trajectory.h",
        "vehicle_dynamics.h",
    ],
    visibility = ["//visibility:public"],
)
