package(default_visibility = ["//bazel/toolchain/clang:__pkg__"])

filegroup(
    name = "ar",
    srcs = [
        "llvm-ar",
        "@llvm_toolchain//:llvm-ar",
    ],
)

filegroup(
    name = "cpp",
    srcs = [
        "clang-cpp",
        "@llvm_toolchain//:clang-cpp",
    ],
)

filegroup(
    name = "cc",
    srcs = [
        "clang++",
        "@llvm_toolchain//:clang++",
    ],
)

filegroup(
    name = "lcov",
    srcs = [
        "llvm-cov",
        "@llvm_toolchain//:llvm-cov",
    ],
)

filegroup(
    name = "ld",
    srcs = [
        "lld",
        "@llvm_toolchain//:lld",
    ],
)

filegroup(
    name = "nm",
    srcs = [
        "llvm-nm",
        "@llvm_toolchain//:llvm-nm",
    ],
)
