load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "timer",
    srcs = ["chrono_timer.cpp"],
    hdrs = [
        "chrono_timer.h",
        "i_timer.h",
    ],
    visibility = ["//visibility:public"],
)
